"""
numero = float(input('Digite um número: '))

print('{:.0f} x 1 = {:.0f}'.format(numero, numero*1))
print('{:.0f} x 2 = {:.0f}'.format(numero, numero*2))
print('{:.0f} x 3 = {:.0f}'.format(numero, numero*3))
print('{:.0f} x 4 = {:.0f}'.format(numero, numero*4))
print('{:.0f} x 5 = {:.0f}'.format(numero, numero*5))
print('{:.0f} x 6 = {:.0f}'.format(numero, numero*6))
print('{:.0f} x 7 = {:.0f}'.format(numero, numero*7))
print('{:.0f} x 8 = {:.0f}'.format(numero, numero*8))
print('{:.0f} x 9 = {:.0f}'.format(numero, numero*9))
print('{:.0f} x 10 = {:.0f}'.format(numero, numero*10))
"""

numero = int(input('Digite um numero para ver sua tabuada: '))
print('-'*12)
print('{} x {:2} = {}'.format(numero, 1, numero*1))
print('{} x {:2} = {}'.format(numero, 2, numero*2))
print('{} x {:2} = {}'.format(numero, 3, numero*3))
print('{} x {:2} = {}'.format(numero, 4, numero*4))
print('{} x {:2} = {}'.format(numero, 5, numero*5))
print('{} x {:2} = {}'.format(numero, 6, numero*6))
print('{} x {:2} = {}'.format(numero, 7, numero*7))
print('{} x {:2} = {}'.format(numero, 8, numero*8))
print('{} x {:2} = {}'.format(numero, 9, numero*9))
print('{} x {:2} = {}'.format(numero, 10, numero*10))
print('-'*12)